# Generated by Django 3.2.20 on 2023-09-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='name@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='password_hash',
            field=models.CharField(default='harsh123', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='registration_date',
            field=models.DateTimeField(default='2000-01-01T00:00:00Z'),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='name_surname', max_length=50),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=100)),
                ('expiry_timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
